[package]
name = "testing"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[workspace]
members = [
    "requires-linker"
]

[build-dependencies]
[build-dependencies.requires-linker]
path = "requires-linker"
artifact = "bin"